# Mock lead data for testing
mock_leads = [
    {
        "id": "1",
        "name": "Kwik Brain",
        "city": "NY",
        "state": "NY",
        "first_name": "Jim",
        "last_name": "Kwik",
        "email": "jim@kwiklearning.com",
        "title": "Founder",
        "website": "http://www.kwikbrain.com",
        "linkedin_url": "http://www.linkedin.com/company/kwik-learning",
        "industry": "Education",
        "revenue": "11.7M",
        "product_service": "Kwik Learning is a global leader in memory improvement and speed reading",
        "business_type": "B2B/B2C",
        "employees": "19",
        "year_founded": "2001",
        "owner_linkedin": "https://www.linkedin.com/in/jimkwik/",
        "score": None
    },
    {
        "id": "2",
        "name": "TechFlow Solutions",
        "city": "San Francisco",
        "state": "CA",
        "first_name": "Sarah",
        "last_name": "Chen",
        "email": "sarah@techflow.com",
        "title": "CEO",
        "website": "https://techflow.com",
        "linkedin_url": "https://linkedin.com/company/techflow-solutions",
        "industry": "Technology",
        "revenue": "25.3M",
        "product_service": "AI-powered workflow automation platform",
        "business_type": "B2B",
        "employees": "45",
        "year_founded": "2018",
        "owner_linkedin": "https://linkedin.com/in/sarahchen",
        "score": None
    },
    {
        "id": "3",
        "name": "GreenTech Innovations",
        "city": "Austin",
        "state": "TX",
        "first_name": "Michael",
        "last_name": "Rodriguez",
        "email": "mike@greentech.com",
        "title": "Founder",
        "website": "https://greentechinnovations.com",
        "linkedin_url": "https://linkedin.com/company/greentech-innovations",
        "industry": "Energy",
        "revenue": "8.9M",
        "product_service": "Renewable energy management systems",
        "business_type": "B2B",
        "employees": "32",
        "year_founded": "2019",
        "owner_linkedin": "https://linkedin.com/in/michaelrodriguez",
        "score": None
    },
    {
        "id": "4",
        "name": "HealthSync Pro",
        "city": "Boston",
        "state": "MA",
        "first_name": "Dr. Emily",
        "last_name": "Watson",
        "email": "emily@healthsync.com",
        "title": "CEO",
        "website": "https://healthsyncpro.com",
        "linkedin_url": "https://linkedin.com/company/healthsync-pro",
        "industry": "Healthcare",
        "revenue": "18.7M",
        "product_service": "Healthcare data synchronization platform",
        "business_type": "B2B",
        "employees": "67",
        "year_founded": "2016",
        "owner_linkedin": "https://linkedin.com/in/emilywatson",
        "score": None
    },
    {
        "id": "5",
        "name": "FinTech Dynamics",
        "city": "New York",
        "state": "NY",
        "first_name": "Alex",
        "last_name": "Thompson",
        "email": "alex@fintechdynamics.com",
        "title": "Founder",
        "website": "https://fintechdynamics.com",
        "linkedin_url": "https://linkedin.com/company/fintech-dynamics",
        "industry": "Finance",
        "revenue": "42.1M",
        "product_service": "Blockchain-based financial services platform",
        "business_type": "B2B",
        "employees": "89",
        "year_founded": "2017",
        "owner_linkedin": "https://linkedin.com/in/alexthompson",
        "score": None
    },
    {
        "id": "6",
        "name": "EduTech Pioneers",
        "city": "Seattle",
        "state": "WA",
        "first_name": "Lisa",
        "last_name": "Park",
        "email": "lisa@edutechpioneers.com",
        "title": "CEO",
        "website": "https://edutechpioneers.com",
        "linkedin_url": "https://linkedin.com/company/edutech-pioneers",
        "industry": "Education",
        "revenue": "15.6M",
        "product_service": "Virtual reality educational content platform",
        "business_type": "B2B/B2C",
        "employees": "38",
        "year_founded": "2020",
        "owner_linkedin": "https://linkedin.com/in/lisapark",
        "score": None
    },
    {
        "id": "7",
        "name": "RetailTech Solutions",
        "city": "Chicago",
        "state": "IL",
        "first_name": "David",
        "last_name": "Miller",
        "email": "david@retailtech.com",
        "title": "Founder",
        "website": "https://retailtechsolutions.com",
        "linkedin_url": "https://linkedin.com/company/retailtech-solutions",
        "industry": "Retail",
        "revenue": "12.3M",
        "product_service": "AI-powered retail analytics and optimization",
        "business_type": "B2B",
        "employees": "41",
        "year_founded": "2018",
        "owner_linkedin": "https://linkedin.com/in/davidmiller",
        "score": None
    },
    {
        "id": "8",
        "name": "CustomGuide Training",
        "city": "Minneapolis",
        "state": "MN",
        "first_name": "Rachel",
        "last_name": "Garcia",
        "email": "rachel@customguide.com",
        "title": "CEO",
        "website": "http://www.customguide.com/",
        "linkedin_url": "https://linkedin.com/company/customguide",
        "industry": "Education",
        "revenue": "31.8M",
        "product_service": "All-in-One training solution with customizable courses and AI course builder",
        "business_type": "B2B",
        "employees": "73",
        "year_founded": "2015",
        "owner_linkedin": "https://linkedin.com/in/rachelgarcia",
        "score": None
    },
    {
        "id": "9",
        "name": "BioTech Innovations",
        "city": "San Diego",
        "state": "CA",
        "first_name": "Dr. James",
        "last_name": "Wilson",
        "email": "james@biotechinnovations.com",
        "title": "Founder",
        "website": "https://biotechinnovations.com",
        "linkedin_url": "https://linkedin.com/company/biotech-innovations",
        "industry": "Biotechnology",
        "revenue": "28.4M",
        "product_service": "CRISPR gene editing technology platform",
        "business_type": "B2B",
        "employees": "56",
        "year_founded": "2019",
        "owner_linkedin": "https://linkedin.com/in/jameswilson",
        "score": None
    },
    {
        "id": "10",
        "name": "MarketingAI Pro",
        "city": "Miami",
        "state": "FL",
        "first_name": "Jessica",
        "last_name": "Brown",
        "email": "jessica@marketingai.com",
        "title": "CEO",
        "website": "https://marketingaipro.com",
        "linkedin_url": "https://linkedin.com/company/marketingai-pro",
        "industry": "Marketing",
        "revenue": "9.7M",
        "product_service": "AI-driven marketing automation platform",
        "business_type": "B2B",
        "employees": "29",
        "year_founded": "2021",
        "owner_linkedin": "https://linkedin.com/in/jessicabrown",
        "score": None
    },
    {
        "id": "11",
        "name": "LogisticsTech",
        "city": "Atlanta",
        "state": "GA",
        "first_name": "Robert",
        "last_name": "Davis",
        "email": "robert@logisticstech.com",
        "title": "Founder",
        "website": "https://logisticstech.com",
        "linkedin_url": "https://linkedin.com/company/logisticstech",
        "industry": "Logistics",
        "revenue": "22.6M",
        "product_service": "Supply chain optimization and tracking platform",
        "business_type": "B2B",
        "employees": "52",
        "year_founded": "2017",
        "owner_linkedin": "https://linkedin.com/in/robertdavis",
        "score": None
    },
    {
        "id": "12",
        "name": "CyberSecure Solutions",
        "city": "Washington",
        "state": "DC",
        "first_name": "Amanda",
        "last_name": "Johnson",
        "email": "amanda@cybersecure.com",
        "title": "CEO",
        "website": "https://cybersecuresolutions.com",
        "linkedin_url": "https://linkedin.com/company/cybersecure-solutions",
        "industry": "Cybersecurity",
        "revenue": "35.2M",
        "product_service": "Advanced threat detection and response system",
        "business_type": "B2B",
        "employees": "78",
        "year_founded": "2016",
        "owner_linkedin": "https://linkedin.com/in/amandajohnson",
        "score": None
    },
    {
        "id": "13",
        "name": "RealEstateTech",
        "city": "Los Angeles",
        "state": "CA",
        "first_name": "Carlos",
        "last_name": "Martinez",
        "email": "carlos@realestatetech.com",
        "title": "Founder",
        "website": "https://realestatetech.com",
        "linkedin_url": "https://linkedin.com/company/realestatetech",
        "industry": "Real Estate",
        "revenue": "14.8M",
        "product_service": "Virtual property tours and market analysis platform",
        "business_type": "B2B/B2C",
        "employees": "34",
        "year_founded": "2020",
        "owner_linkedin": "https://linkedin.com/in/carlosmartinez",
        "score": None
    },
    {
        "id": "14",
        "name": "FoodTech Innovations",
        "city": "Portland",
        "state": "OR",
        "first_name": "Maria",
        "last_name": "Anderson",
        "email": "maria@foodtech.com",
        "title": "CEO",
        "website": "https://foodtechinnovations.com",
        "linkedin_url": "https://linkedin.com/company/foodtech-innovations",
        "industry": "Food & Beverage",
        "revenue": "7.3M",
        "product_service": "Plant-based food production technology",
        "business_type": "B2B",
        "employees": "23",
        "year_founded": "2021",
        "owner_linkedin": "https://linkedin.com/in/mariaanderson",
        "score": None
    },
    {
        "id": "15",
        "name": "LegalTech Solutions",
        "city": "Philadelphia",
        "state": "PA",
        "first_name": "Thomas",
        "last_name": "Clark",
        "email": "thomas@legaltech.com",
        "title": "Founder",
        "website": "https://legaltechsolutions.com",
        "linkedin_url": "https://linkedin.com/company/legaltech-solutions",
        "industry": "Legal",
        "revenue": "19.5M",
        "product_service": "AI-powered legal document automation platform",
        "business_type": "B2B",
        "employees": "44",
        "year_founded": "2018",
        "owner_linkedin": "https://linkedin.com/in/thomasclark",
        "score": None
    },
    {
        "id": "16",
        "name": "HRTech Pro",
        "city": "Nashville",
        "state": "TN",
        "first_name": "Jennifer",
        "last_name": "Taylor",
        "email": "jennifer@hrtechpro.com",
        "title": "CEO",
        "website": "https://hrtechpro.com",
        "linkedin_url": "https://linkedin.com/company/hrtech-pro",
        "industry": "Human Resources",
        "revenue": "11.2M",
        "product_service": "Employee engagement and performance management platform",
        "business_type": "B2B",
        "employees": "31",
        "year_founded": "2019",
        "owner_linkedin": "https://linkedin.com/in/jennifertaylor",
        "score": None
    },
    {
        "id": "17",
        "name": "TravelTech Solutions",
        "city": "Orlando",
        "state": "FL",
        "first_name": "Kevin",
        "last_name": "White",
        "email": "kevin@traveltech.com",
        "title": "Founder",
        "website": "https://traveltechsolutions.com",
        "linkedin_url": "https://linkedin.com/company/traveltech-solutions",
        "industry": "Travel",
        "revenue": "16.9M",
        "product_service": "AI-powered travel booking and recommendation platform",
        "business_type": "B2B/B2C",
        "employees": "39",
        "year_founded": "2017",
        "owner_linkedin": "https://linkedin.com/in/kevinwhite",
        "score": None
    },
    {
        "id": "18",
        "name": "SportsTech Innovations",
        "city": "Dallas",
        "state": "TX",
        "first_name": "Nicole",
        "last_name": "Lee",
        "email": "nicole@sportstech.com",
        "title": "CEO",
        "website": "https://sportstechinnovations.com",
        "linkedin_url": "https://linkedin.com/company/sportstech-innovations",
        "industry": "Sports",
        "revenue": "8.4M",
        "product_service": "Athletic performance tracking and analytics platform",
        "business_type": "B2B/B2C",
        "employees": "26",
        "year_founded": "2020",
        "owner_linkedin": "https://linkedin.com/in/nicolelee",
        "score": None
    },
    {
        "id": "19",
        "name": "MediaTech Pro",
        "city": "Austin",
        "state": "TX",
        "first_name": "Daniel",
        "last_name": "Harris",
        "email": "daniel@mediatech.com",
        "title": "Founder",
        "website": "https://mediatechpro.com",
        "linkedin_url": "https://linkedin.com/company/mediatech-pro",
        "industry": "Media",
        "revenue": "13.7M",
        "product_service": "Content creation and distribution automation platform",
        "business_type": "B2B",
        "employees": "36",
        "year_founded": "2019",
        "owner_linkedin": "https://linkedin.com/in/danielharris",
        "score": None
    },
    {
        "id": "20",
        "name": "AgriTech Solutions",
        "city": "Des Moines",
        "state": "IA",
        "first_name": "Patricia",
        "last_name": "Moore",
        "email": "patricia@agritech.com",
        "title": "CEO",
        "website": "https://agritechsolutions.com",
        "linkedin_url": "https://linkedin.com/company/agritech-solutions",
        "industry": "Agriculture",
        "revenue": "6.8M",
        "product_service": "Precision agriculture and crop monitoring platform",
        "business_type": "B2B",
        "employees": "21",
        "year_founded": "2021",
        "owner_linkedin": "https://linkedin.com/in/patriciamoore",
        "score": None
    }
] 